### PR TITLE
#184638367 Configure Swagger 

### PR DESCRIPTION
**Pull request by felixdusengimana**
**What does this PR do?**

To have swagger configured.

**Description of Task to be completed?**

Configuring swagger to make API documentation more organized and accessible to other developers.

**How should this be manually tested?**
After checking out of my branch, run ` npm install ` for added dependencies.
 you can then start application with `npm run dev` after you can access docs to this url `http://localhost:3000/api-docs/` .

**Any background context you want to provide?**

For those who don't know how to use `swaggify`, it is highly advised to read the documentation via [https://github.com/divinirakiza/swaggiffy](https://github.com/divinirakiza/swaggiffy) and also view example projects via [https://github.com/divinirakiza/swaggify-samples](https://github.com/divinirakiza/swaggify-samples).

**What are the relevant pivotal tracker stories?**

#184638367

### CODE REVIEW

**Review by honorine22 — APPROVED** [review]
It works for me after checking out your branch.

**Review by didiermun — APPROVED** [review]
Looks good to me

**Review by oreste-abizera — APPROVED** [review]
All set to go!

**Review by edine-noella — APPROVED** [review]

**Review by divinrkz — APPROVED** [review]

**Comment by dushimsam** [comment]
Looks great

**Review by dushimsam — APPROVED** [review]
Looks great

**Review by Nkbtemmy — CHANGES_REQUESTED** [review]
Those commits are too much; I want you to squash them into only one commit

**Pull request closed without merging**
