### PR TITLE
#184639260 env setup and database variables

### PR DESCRIPTION
**Pull request by oreste-abizera**
**What does this PR do?**
.env file setup and database env variables storage

**Description of Task to be completed?**
Environment variables are stored in .env file and accessed through the app

**How should this be manually tested?**
- Duplicate .env.example file and rename it to .env and provide the values to variables in it or add new variables.
- access your variables within the app using process.env

**What are the relevant pivot tracker stories**
[#184639260](https://www.pivotaltracker.com/story/show/184639260)

### CODE REVIEW

**Comment by dushimsam** [comment]
Looks good, but you need to resolve all the CI/CD checks.

**Comment by oreste-abizera** [comment]
> Looks good, but you need to resolve all the CI/CD checks.

@dushimsam the build script isn't set up yet for Build CI and config.yml is not set up for CircleCI Pipeline. You can coordinate on their merge to unblock this PR.

**Comment by dushimsam** [comment]
> > Looks good, but you need to resolve all the CI/CD checks.
> 
> @dushimsam the build script isn't set up yet for Build CI and config.yml is not set up for CircleCI Pipeline. You can coordinate on their merge to unblock this PR.

I think @divinirakiza  should keep up with this issue

**Review by Nkbtemmy — APPROVED** [review]

**Review by divinrkz — APPROVED** [review]

**Review by didiermun — APPROVED** [review]
Good to go

**Pull request merged**
