### PR TITLE
#184639058 Project structure with up and running express server

### PR DESCRIPTION
**Pull request by didiermun**
#### What does this PR do?
Creates an express server while also setting up project initial structure
#### Description of Task to be completed?
Has first-end point ``GET /`` and basic folder structure for more work in future.
#### How should this be manually tested?
Close this repository, and install dependencies with ``npm install``, next ``npm run dev`` and check ``http://localhost:3000``
#### Any background context you want to provide?
We are using express server currently, and the only package necessary
#### What are the relevant pivotal tracker stories?
None

### CODE REVIEW

**Review by dushimsam — COMMENTED** [review]
Looks good to me

**Review by Nkbtemmy — APPROVED** [review]

**Comment by Nkbtemmy** [comment]
> Looks good to me

This is a comment; so if you see and want to approve his work; go on and approve; because messages only are like notifications about changes you want him to do.

**Comment by divinrkz** [comment]
This is it!

**Review by divinrkz — APPROVED** [review]

**Review by edine-noella — APPROVED** [review]
Good to go !

**Pull request merged**
